apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store  
    spec:
      containers:
        - name: store-client
          image: fungroup10/store-client:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
